{
 "title": "Canary",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Canary Runs Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(startworkflow{type=\"canary\"}[5m]) * 60)",
     "legendFormat": "Start Sanity Workflow"
    },
    {
     "expr": "sum (rate(startworkflow_success{type=\"canary\"}[5m]) * 60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum (rate(startworkflow_failures{type=\"canary\"}[5m]) * 60)",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Sanity Start Failure - Breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(startworkflow_failures_alreadystarted{type=\"canary\"}[5m])*60"
    },
    {
     "expr": "rate(startworkflow_failures_namespacenotactive{type=\"canary\"}[5m])*60"
    }
   ]
  },
  {
   "title": "Sanity - Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workflow_started{WorkflowType=~\"workflow.sanity\", type=\"canary\"}[5m]))*60",
     "legendFormat": "Started - {{WorkflowType}}"
    },
    {
     "expr": "sum(rate(workflow_failed{WorkflowType=~\"workflow.sanity\", type=\"canary\"}[5m])*60)",
     "legendFormat": "Failed - {{WorkflowType}}"
    },
    {
     "expr": "sum(rate(workflow_succeeded{WorkflowType=~\"workflow.sanity\", type=\"canary\"}[5m])*60)",
     "legendFormat": "Succeeded - {{WorkflowType}}"
    }
   ]
  },
  {
   "title": "Sanity - Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workflow_latency_bucket{WorkflowType=~\"workflow.sanity\", type=\"canary\"}[5m])) by (WorkflowType, le))",
     "legendFormat": "{{WorkflowType}}"
    }
   ]
  },
  {
   "title": "Workflow Starts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (WorkflowType) (rate(workflow_started{type=\"canary\"}[5m]))* 60",
     "legendFormat": "{{WorkflowType}}"
    }
   ]
  },
  {
   "title": "Workflow Success",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (WorkflowType) (rate(workflow_succeeded{type=\"canary\"}[5m]))* 60",
     "legendFormat": "{{WorkflowType}}"
    }
   ]
  },
  {
   "title": "Workflow Failed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Workflow Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workflow_latency_bucket{type=\"canary\"}[5m])) by (WorkflowType, le))",
     "legendFormat": "{{WorkflowType}}"
    }
   ]
  }
 ]
}