{
 "title": "Common",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "frontend,history,matching,worker"
   }
  ]
 },
 "panels": [
  {
   "title": "Service - $Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(service_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(service_errors{type=~\"$Service\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(service_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Break Down",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(service_errors_entity_not_found{type=~\"$Service\"}[5m]))",
       "legendFormat": "Entity Not Found"
      },
      {
       "expr": "sum(rate(service_errors_execution_already_started{type=~\"$Service\"}[5m]))",
       "legendFormat": "Execution Already Started"
      },
      {
       "expr": "sum(rate(service_errors_resource_exhausted{type=~\"$Service\"}[5m]))",
       "legendFormat": "Resource Exhausted"
      },
      {
       "expr": "sum by (__name__) (rate({__name__=~\"service_errors_.*\", type=~\"$Service\"}[5m]))",
       "legendFormat": "{{ $__name__ }}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{type=~\"$Service\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Vs Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(persistence_requests{type=~\"$Service\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(persistence_errors{type=~\"$Service\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(persistence_requests{type=\"frontend\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Break Down",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "legendFormat": "{{operation}}" }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(persistence_latency_bucket{type=\"frontend\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "History Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_requests{type=\"frontend\", service_role=\"history\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(client_errors{type=\"frontend\", service_role=\"history\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_requests{type=\"frontend\", service_role=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_errors{type=\"frontend\", service_role=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket{type=\"frontend\", service_role=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Matching Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(client_requests{type=\"frontend\", service_role=\"matching\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(client_errors{type=\"frontend\", service_role=\"matching\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_requests{type=\"frontend\", service_role=\"matching\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_errors{type=\"frontend\", service_role=\"matching\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket{type=\"frontend\", service_role=\"matching\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}