{
 "title": "ES Visibility",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(service_requests,cluster)"
   },
   {
    "name": "service",
    "query": "label_values(service_requests,service)"
   }
  ]
 },
 "panels": [
  { "title": "ES persistence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests VS Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_requests{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(elasticsearch_errors{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum (rate(elasticsearch_errors_bad_request{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "bad request"
    },
    {
     "expr": "sum (rate(elasticsearch_errors_busy{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "busy"
    }
   ]
  },
  {
   "title": "Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(elasticsearch_requests{cluster=\"$cluster\",temporal_service_type=\"history\",service=\"$service\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors Per Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(elasticsearch_errors{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "{{operation}} error"
    },
    {
     "expr": "sum by (operation) (rate(elasticsearch_errors_bad_request{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "{{operation}} bad request"
    },
    {
     "expr": "sum by (operation) (rate(elasticsearch_errors_busy{cluster=\"$cluster\",service=\"$service\"}[1m]))",
     "legendFormat": "{{operation}} busy"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (operation) (rate(elasticsearch_latency_sum{cluster=\"$cluster\",service=\"$service\"}[1m]))) / (sum by (operation) (rate(elasticsearch_latency_count{cluster=\"$cluster\",service=\"$service\"}[1m])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(elasticsearch_latency_bucket{cluster=\"$cluster\",service=\"$service\"}[1m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(elasticsearch_latency_bucket{cluster=\"$cluster\",service=\"$service\"}[1m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Bulk Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "ES Bulk Processor Requests And Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(es_bulk_processor_requests{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(es_bulk_processor_errors{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum (rate(es_bulk_processor_retries{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "retries"
    },
    {
     "expr": "sum (rate(es_bulk_processor_corrupted_data{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "corrupted data"
    },
    {
     "expr": "sum (rate(es_invalid_search_attribute{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "invalid search attribute"
    }
   ]
  },
  {
   "title": "Avg Bulk Processor Processing Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(es_bulk_processor_request_latency_sum{cluster=\"$cluster\"}[1m]))) / (sum(rate(es_bulk_processor_request_latency_count{cluster=\"$cluster\"}[1m])))",
     "legendFormat": "request_latency"
    }
   ]
  }
 ]
}