{
 "title": "History",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "History Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(service_requests{type=\"history\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(service_errors{type=\"history\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(service_requests{type=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Per Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 13, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate({__name__=~\"service_errors_.*\", type=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Break Down",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(service_errors_entity_not_found{type=\"history\"}[5m]))",
       "legendFormat": "Entity Not Found"
      },
      {
       "expr": "sum(rate(service_errors_execution_already_started{type=\"hisotry\"}[5m]))",
       "legendFormat": "Execution Already Started"
      },
      {
       "expr": "sum(rate(service_errors_resource_exhausted{type=\"history\"}[5m]))",
       "legendFormat": "Resource Exhausted"
      },
      {
       "expr": "sum by (__name__) (rate({__name__=~\"service_errors_.*\", type=\"history\"}[5m]))",
       "legendFormat": "{{ $__name__ }}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transfer Tasks Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Transfer Task Requests Vs Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_requests{operation=~\"TransferActive.*\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(task_errors{operation=~\"TransferActive.*\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Active Transfer Task By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(task_requests{operation=~\"TransferActive.*\"}[5m]))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Transfer Task Errors By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(task_errors{operation=~\"TransferActive.*\"}[5m]))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Transfer Errors Breakdown",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(task_errors_discarded{operation=~\"TransferActive.*\"}[5m]))",
       "legendFormat": "discarded"
      },
      {
       "expr": "sum (rate(task_errors_limit_exceeded_counter{operation=~\"TransferActive.*\"}[5m]))"
      }
     ]
    },
    {
     "title": "Active Transfer Task Processing Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(task_latency_processing_bucket{operation=~\"TransferActive.*\", type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Transfer Task Total Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(task_latency_bucket{operation=~\"TransferActive.*\", type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Transfer Task Queue Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(task_latency_queue_bucket{operation=~\"TransferActive.*\", type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Transfer Task Attempt Stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_attempt_bucket{operation=\"TransferActiveTaskCommand\", type=\"history\"}[5m])) by (le)"
      }
     ]
    }
   ]
  },
  {
   "title": "Timer Tasks Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Timer Task Requests Vs Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_requests{operation=~\"TimerActive.*\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(task_errors{operation=~\"TimerActive.*\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Active Timer Task By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(task_requests{operation=~\"TimerActive.*\"}[5m]))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Timer Task Errors By Operation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(task_errors{operation=~\"TimerActive.*\"}[5m]))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Timer Errors Breakdown",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(task_errors_discarded{operation=~\"TimerActive.*\"}[5m]))",
       "legendFormat": "discarded"
      },
      {
       "expr": "sum (rate(task_errors_limit_exceeded_counter{operation=~\"TimerActive.*\"}[5m]))"
      }
     ]
    },
    {
     "title": "Active Timer Task Processing Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(task_latency_processing_bucket{operation=~\"TimerActive.*\", type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Timer Task Total Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(task_latency_bucket{operation=~\"TimerActive.*\", type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Timer Task Queue Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(task_latency_queue_bucket{operation=~\"TimerActive.*\", type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Active Timer Task Attempt Stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_attempt_bucket{operation=\"TimerActiveTaskCommand\", type=\"history\"}[5m])) by (le)"
      }
     ]
    }
   ]
  },
  {
   "title": "Mutable State Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mutable State Cache Requests By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation)(rate(cache_requests{cache_type=\"mutablestate\"}[5m]))",
       "legendFormat": "{{operation}} - requests"
      }
     ]
    },
    {
     "title": "Mutable State Cache Miss By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation)(rate(cache_miss{cache_type=\"mutablestate\"}[5m]))",
       "legendFormat": "{{operation}} - cache_miss"
      }
     ]
    },
    {
     "title": "Mutable State Cache",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
       "legendFormat": "cache_requests"
      },
      {
       "expr": "sum(rate(cache_errors{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
       "legendFormat": "cache_failures"
      },
      {
       "expr": "sum(rate(cache_miss{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
       "legendFormat": "cache_miss"
      },
      {
       "expr": "sum(rate(acquire_lock_failed{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m]))",
       "legendFormat": "acquire_lock_failed"
      }
     ]
    },
    {
     "title": "Mutable State Cache Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cache_type=\"mutablestate\", operation!~\"HistoryCacheGetCurrentExecution\"}[5m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "Mutable State Load Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cache_type=\"mutablestate\", operation=\"HistoryCacheGetCurrentExecution\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(cache_errors{cache_type=\"mutablestate\", operation=\"HistoryCacheGetCurrentExecution\"}[5m]))",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "Mutable State Load Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cache_type=\"mutablestate\", operation=\"HistoryCacheGetCurrentExecution\"}[5m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "GetOrCreate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
       "legendFormat": "cache_requests"
      },
      {
       "expr": "sum(rate(cache_errors{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
       "legendFormat": "cache_errors"
      },
      {
       "expr": "sum(rate(cache_miss{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
       "legendFormat": "cache_miss"
      },
      {
       "expr": "sum(rate(acquire_lock_failed{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreate\"}[5m]))",
       "legendFormat": "acquire_lock_failed"
      }
     ]
    },
    {
     "title": "GetOrCreateCurrent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
       "legendFormat": "cache_requests"
      },
      {
       "expr": "sum(rate(cache_errors{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
       "legendFormat": "cache_errors"
      },
      {
       "expr": "sum(rate(cache_miss{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
       "legendFormat": "cache_miss"
      },
      {
       "expr": "sum(rate(acquire_lock_failed{cache_type=\"mutablestate\", operation=\"HistoryCacheGetOrCreateCurrent\"}[5m]))",
       "legendFormat": "acquire_lock_failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Events Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Cache - Overview",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation)(rate(cache_requests{cache_type=\"events\"}[5m]))"
      },
      {
       "expr": "sum by (operation) (rate(cache_miss{cache_type=\"events\"}[5m]))",
       "legendFormat": "{{ operation }} - cache_miss"
      }
     ]
    },
    {
     "title": "Get Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation)(rate(cache_requests{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum by (operation)(rate(cache_miss{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m]))",
       "legendFormat": "cache_miss"
      },
      {
       "expr": "sum by (operation)(rate(cache_errors{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Get Events Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cache_type=\"events\", operation=\"EventsCacheGetEvent\"}[5m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "Put Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cache_type=\"events\", operation=\"EventsCachePutEvent\"}[5m]))",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Put Events Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cache_type=\"events\", operation=\"EventsCachePutEvent\"}[5m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "Get Events From Store",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cache_requests{cache_type=\"events\", operation=\"EventsCacheGetFromStore\"}[5m]))",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Get Events From Store Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cache_latency_bucket{cache_type=\"events\", operation=\"EventsCacheGetFromStore\"}[5m])) by (le))",
       "legendFormat": "latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Task Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Task Break Down",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(schedule_activity_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "schedule_activity"
      },
      {
       "expr": "sum(rate(complete_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "complete_workflow"
      },
      {
       "expr": "sum(rate(fail_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "fail_workflow"
      },
      {
       "expr": "sum(rate(cancel_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "cancel_workflow"
      },
      {
       "expr": "sum(rate(start_timer_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "start_timer"
      },
      {
       "expr": "sum(rate(cancel_activity_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "cancel_activity"
      },
      {
       "expr": "sum(rate(cancel_timer_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "cancel_timer"
      },
      {
       "expr": "sum(rate(record_marker_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "record_marker"
      },
      {
       "expr": "sum(rate(cancel_external_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "cancel_external_workflow"
      },
      {
       "expr": "sum(rate(continue_as_new_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "continue_as_new"
      },
      {
       "expr": "sum(rate(signal_external_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "signal_external_workflow"
      },
      {
       "expr": "sum(rate(upsert_workflow_search_attributes_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "upsert_searchable_attributes"
      },
      {
       "expr": "sum(rate(child_workflow_command{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "child_workflow"
      }
     ]
    },
    {
     "title": "Sticky Vs Non Sticky",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(service_requests{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "commands_complete"
      },
      {
       "expr": "sum(rate(complete_workflow_task_sticky_enabled_count{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "sticky_tasks"
      },
      {
       "expr": "sum(rate(complete_workflow_task_sticky_disabled_count{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "non_sticky_tasks"
      }
     ]
    },
    {
     "title": "Failed Workflow Task",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(failed_workflow_tasks{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Empty Workflow Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(empty_completion_commands{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "empty_decision"
      }
     ]
    },
    {
     "title": "Multiple Complete Workflows",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(multiple_completion_commands{type=\"history\", operation=\"RespondWorkflowTaskCompleted\"}[5m]))",
       "legendFormat": "empty_workflow"
      }
     ]
    }
   ]
  },
  {
   "title": "Mutable State Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stale Mutable State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(stale_mutable_state{type=\"history\"}[5m]))",
       "legendFormat": "{{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shard Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Acquire Shards Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(acquire_shards_count[5m]))",
       "legendFormat": "acquire"
      }
     ]
    },
    {
     "title": "Acquire Shards Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(acquire_shards_latency_bucket{type=\"history\"}[5m])) by (le))",
       "legendFormat": "acquire_latency"
      }
     ]
    },
    {
     "title": "Shards Closed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(shard_closed_count[5m]))",
       "legendFormat": "shards_closed"
      }
     ]
    },
    {
     "title": "Shard Item Counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sharditem_created_count[5m]))",
       "legendFormat": "item_created"
      },
      {
       "expr": "sum(rate(sharditem_removed_count[5m]))",
       "legendFormat": "item_removed"
      }
     ]
    },
    {
     "title": "Shard Item Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(sharditem_acquisition_latency{type=\"history\"}[5m])) by (le))",
       "legendFormat": "acquire_latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Vs Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(persistence_requests{type=\"history\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(persistence_errors{type=\"history\"}[5m]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(persistence_requests{type=\"history\"}[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors Break Down",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "legendFormat": "{{operation}}" }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(persistence_latency_bucket{type=\"history\"}[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}