{
 "title": "SDK",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "canary,temporal-bench,temporal_system"
   },
   { "name": "WorkflowType", "query": "cronWorkflow,workflow_sanity" }
  ]
 },
 "panels": [
  { "title": "RPC Overview ($Namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Vs Failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(temporal_request{Namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(temporal_request_failure{Namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "RPC Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (Operation) ((rate(temporal_request{Namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ Operation }}"
    }
   ]
  },
  {
   "title": "RPC Failures Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (Operation) (rate(temporal_request_failure{Namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ Operation }}"
    }
   ]
  },
  {
   "title": "RPC Latencies ($Namespace)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (Namespace, Operation, le) (rate(temporal_request_latency_bucket{Namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ Namespace }} - {{ Operation }}"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Completion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(temporal_workflow_completed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(temporal_workflow_failed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(temporal_workflow_canceled{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "canceled"
      },
      {
       "expr": "sum(rate(temporal_workflow_continue_as_new{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "continued_as_new"
      }
     ]
    },
    {
     "title": "Workflow End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_endtoend_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, WorkflowType, le))",
       "legendFormat": "{{ Namespace }} - {{ WorkflowType }}"
      }
     ]
    },
    {
     "title": "Workflow Success By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace, WorkflowType) (rate(temporal_workflow_completed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }} - {{ WorkflowType }}"
      }
     ]
    },
    {
     "title": "Workflow Failures By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace, WorkflowType) (rate(temporal_workflow_failed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }} - {{ WorkflowType }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Task Throughput By WorkflowType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace, WorkflowType) (rate(temporal_workflow_task_queue_poll_succeed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }} - {{ WorkflowType }}"
      }
     ]
    },
    {
     "title": "Workflow Task Throughput By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_workflow_task_queue_poll_succeed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Empty Polls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_workflow_task_queue_poll_empty{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "Empty Poll - {{ Namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, le))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, WorkflowType, le))",
       "legendFormat": "{{ Namespace }} -- {{ WorkflowType }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_workflow_task_execution_failed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace, WorkflowType) (rate(temporal_workflow_task_execution_failed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }} -- {{ WorkflowType }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, le))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, WorkflowType, le))",
       "legendFormat": "{{ Namespace }} -- {{ WorkflowType }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, le))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, WorkflowType, le))",
       "legendFormat": "{{ Namespace }} -- {{ WorkflowType }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity Throughput By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_activity_execution_latency_count{Namespace=~\"$Namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Activity Throughput By Activity Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace, ActivityType) (rate(temporal_activity_execution_latency_count{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }} - {{ ActivityType }}"
      }
     ]
    },
    {
     "title": "Failed Activity by Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace, ActivityType) (rate(temporal_activity_execution_failed{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }} - {{ ActivityType }}"
      }
     ]
    },
    {
     "title": "Activity Execution Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, ActivityType, le))",
       "legendFormat": "{{ Namespace }} - {{ ActivityType }}"
      }
     ]
    },
    {
     "title": "Activity End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_endtoend_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, ActivityType, le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Empty Activity Polls By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_activity_poll_no_task{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, le))"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By Activity Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{Namespace=~\"$Namespace\"}[5m])) by (Namespace, ActivityType, le))",
       "legendFormat": "{{ Namespace }} - {{ ActivityType }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sticky Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sticky Cache Hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_sticky_cache_hit{Namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_sticky_cache_miss{Namespace=~\"Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Forced Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (rate(temporal_sticky_cache_total_forced_eviction{Namespace=~\"Namespace\"}[5m]))",
       "legendFormat": "{{ Namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (Namespace) (temporal_sticky_cache_size)",
       "legendFormat": "{{ Namespace }}"
      }
     ]
    }
   ]
  }
 ]
}