{
 "title": "Worker",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(service_requests,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scavengers running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum without (instance, pod) (started{cluster=\"$cluster\"})) - (sum without (instance, pod) (stopped{cluster=\"$cluster\"} or started{cluster=\"$cluster\"}*0))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Completed scan tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_done{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Dropped tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_dropped{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_err{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Deferred tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum without (instance, pod) (rate(executor_deferred{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Executions scavenger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validation Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(rate(scavenger_validation_requests{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "DetailedErrors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pod)(rate(scavenger_validation_failures{cluster=\"$cluster\"}[5m]))",
       "legendFormat": "{{failure}}"
      }
     ]
    },
    {
     "title": "ExecutionsLeftToScan",
     "type": "graph",
     "description": "Might stuck until scavenger rerun in case of worker crash.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pod)(executions_outstanding{cluster=\"$cluster\"})",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskQueue scavenger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Outstanding scavenger tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(taskqueue_outstanding{cluster=\"$cluster\"})",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "Processed taskqueue tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(taskqueue_processed{cluster=\"$cluster\"})",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "Deleted taskqueue tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(taskqueue_deleted{cluster=\"$cluster\"})",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "Processed tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(task_processed{cluster=\"$cluster\"})",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "Deleted tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(task_deleted{cluster=\"$cluster\"})",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "History scavenger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(rate(scavenger_success{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "Skips",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(rate(scavenger_skips{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum without (instance, pod)(rate(scavenger_errors{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "{{k8s_cluster_name}}"
      }
     ]
    }
   ]
  }
 ]
}